# A very simple game in python 

print('What do you get when you cross a snowman with a vampire?')
input()
print('frostbite!')
print()
print('What dou dentists call a astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock Knock')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh',end='')
print('-MOO!')
